function [POD_Table] = ReadFile(filename, researcher)
%% Renaming variables to make less confusing
% This is going to run a check to see who is running this, I custom-wrote
% you a function to import because I know generally what sensors you're
% using among other things, so it's easier to do it this way cause then I
% also get to see if writing data is working and I have more examples for
% Ashwini & Simman and to know what would make POD-use easier in the future
%% Reads File from .txt
POD_Table = readtable(filename, 'TreatAsMissing', "N/A");

%% Sean
if (researcher == "Sean")
    newNames = ["DateTime", "Voltage_In", "Fig1", "Fig2", "Fig3_H", ...
        "Fig3", "Fig4_H", "Fig4", "e2V", "PID", "CO_Main",...
        "CO_Aux", "CO2", "T", "P", "RH", "QS1_Main", "QS1_Aux", ...
        "QS2_Main", "QS2_Aux", "QS3_Main", "QS3_Aux", "QS4_Main", ...
        "QS4_Aux", "Wind_Spd", "Wind_Dir", "MQ", "PT_PM10ENV", ...
        "PT_PM25ENV", "PT_PM100ENV", "PT_PM03um", "PT_PM05um", ...
        "PT_PM10um", "PT_PM25um", "PT_PM50um", "PT_PM100um"];
    POD_Table = renamevars(POD_Table, 1:width(POD_Table), newNames);
end
%% Caroline
if (researcher == "Caroline")
    newNames = ["DateTime", "Voltage_In", "Fig1", "Fig2", "Fig3_H", ...
        "Fig3", "Fig4_H", "Fig4", "e2V", "PID", "CO_Main",...
        "CO_Aux", "CO2", "T", "P", "RH", "O3_Main", "O3_Aux", ...
        "NO2_Main", "NO2_Aux", "H2S_Main", "H2S_Aux", "QS4_Main", ...
        "QS4_Aux", "Wind_Spd", "Wind_Dir", "MQ", "PT_PM10ENV", ...
        "PT_PM25ENV", "PT_PM100ENV", "PT_PM03um", "PT_PM05um", ...
        "PT_PM10um", "PT_PM25um", "PT_PM50um", "PT_PM100um"];
    POD_Table = renamevars(POD_Table, 1:width(POD_Table), newNames);
end
%% Annamarie
if (researcher == "Annamarie")
    newNames = ["DateTime", "Voltage_In", "Fig1", "Fig2", "Fig3_H", ...
        "Fig3", "Fig4_H", "Fig4", "e2V", "PID", "CO_Main",...
        "CO_Aux", "CO2", "T", "P", "RH", "QS1_Main", "QS1_Aux", ...
        "QS2_Main", "QS2_Aux", "QS3_Main", "QS3_Aux", "QS4_Main", ...
        "QS4_Aux", "Wind_Spd", "Wind_Dir", "MQ", "PT_PM10ENV", ...
        "PT_PM25ENV", "PT_PM100ENV", "PT_PM03um", "PT_PM05um", ...
        "PT_PM10um", "PT_PM25um", "PT_PM50um", "PT_PM100um"];
    POD_Table = renamevars(POD_Table, 1:width(POD_Table), newNames);
end
end

